// <auto-generated />
using CinemaBox.Context.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaBox.Context.Migrations
{
    [DbContext(typeof(CinemaBoxDbContext))]
    [Migration("20250614154552_InitialDb_V8")]
    partial class InitialDb_V8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryPartTypes.CountryPartType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CountryPartTypeId")
                        .HasComment("شناسه نوع تقسیم بندی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("CountryPartTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان نوع تقسیم بندی");

                    b.HasKey("Id");

                    b.ToTable("CountryPartTypes", "Division");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CountryPartTypeName = "کشور"
                        },
                        new
                        {
                            Id = (byte)2,
                            CountryPartTypeName = "استان"
                        },
                        new
                        {
                            Id = (byte)3,
                            CountryPartTypeName = "شهرستان"
                        });
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryParts.CountryPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CountryPartId")
                        .HasComment("شناسه کشور");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte?>("CountryPartTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه نوع کشور");

                    b.Property<string>("EnCountryPartName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان انگلیسی");

                    b.Property<string>("FaCountryPartName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان فارسی");

                    b.Property<string>("IsoCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("عنوان نوع تقسیم بندی");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("شناسه پدر");

                    b.HasKey("Id");

                    b.HasIndex("CountryPartTypeId");

                    b.ToTable("CountryParts", "Division");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Certificates.Certificate", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CertificateId")
                        .HasComment("شناسه زده بندی سنی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("نام درجه بندی");

                    b.HasKey("Id");

                    b.ToTable("Certificates", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Collections.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CollectionId")
                        .HasComment("شناسه کالکشن");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnCollectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام کالکشن انگلیسی");

                    b.Property<string>("FaCollectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام کالکشن فارسی");

                    b.HasKey("Id");

                    b.ToTable("Collections", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Coropration.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CompanyId")
                        .HasComment("شناسه شزکت");

                    b.Property<string>("EnCompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان شرکت انگلیسی");

                    b.Property<string>("FaCompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان شرکت فارسی");

                    b.HasKey("Id");

                    b.ToTable("Companies", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCompanies.MovieCompany", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CompanyId")
                        .HasComment("شناسه شرکت");

                    b.HasKey("MovieId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("MovieCompanies", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCountries.MovieCountry", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<long>("CountryPartId")
                        .HasMaxLength(20)
                        .HasColumnType("bigint")
                        .HasColumnName("CountryPartId")
                        .HasComment("شناسه کشور");

                    b.HasKey("MovieId", "CountryPartId");

                    b.HasIndex("CountryPartId");

                    b.ToTable("MovieCountries", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم یا سریال");

                    b.Property<decimal?>("AggregateRating")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("رتبه بندی کل");

                    b.Property<double?>("Budget")
                        .HasColumnType("float")
                        .HasComment("بودجه");

                    b.Property<byte?>("BudgetCurrencyId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه واحد پول بودجه");

                    b.Property<byte?>("CertificateId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه درجه بندی سنی");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int")
                        .HasComment("شناسه کالکشن");

                    b.Property<string>("EnPlot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("خلاصه داستان انگلیسی");

                    b.Property<string>("EnStoryline")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("داستان انگلیسی");

                    b.Property<string>("EnTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان انگلیسی");

                    b.Property<long?>("EndYear")
                        .HasColumnType("bigint")
                        .HasComment("تاریخ پایان سریال");

                    b.Property<string>("FaStoryline")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("داستان فارسی");

                    b.Property<string>("FaTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان فارسی");

                    b.Property<bool?>("IsTvShow")
                        .HasColumnType("bit")
                        .HasComment("سریال");

                    b.Property<long?>("Nomination")
                        .HasColumnType("bigint")
                        .HasComment("نامزد شدن");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان اصلی");

                    b.Property<byte?>("OscarNominations")
                        .HasColumnType("tinyint")
                        .HasComment("تعداد نامزد اسکار");

                    b.Property<byte?>("OscarWins")
                        .HasColumnType("tinyint")
                        .HasComment("تعداد برنده اسکار");

                    b.Property<long?>("ReleaseDay")
                        .HasColumnType("bigint")
                        .HasComment("روز انتشار");

                    b.Property<long?>("ReleaseMonth")
                        .HasColumnType("bigint")
                        .HasComment("ماه انتشار");

                    b.Property<long?>("ReleaseYear")
                        .HasColumnType("bigint")
                        .HasComment("سال انتشار");

                    b.Property<long?>("RunTimeMinutes")
                        .HasColumnType("bigint")
                        .HasComment("مدت زمان فیلم یا سریال");

                    b.Property<long?>("StartYear")
                        .HasColumnType("bigint")
                        .HasComment("سال فیلم یا سال شروع سریال");

                    b.Property<byte?>("TopRank")
                        .HasColumnType("tinyint")
                        .HasComment("برترین فیلم");

                    b.Property<long?>("VoteCount")
                        .HasColumnType("bigint")
                        .HasComment("تعداد رای دهندگان");

                    b.Property<long?>("Winner")
                        .HasColumnType("bigint")
                        .HasComment("تعداد جوایز");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCurrencyId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Movies", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Currencies.Currency", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CurrencyId")
                        .HasComment("شناسه واحد پولی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان واحد پولی");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "Shared");
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryParts.CountryPart", b =>
                {
                    b.HasOne("CinemaBox.Domain.Division.CountryPartTypes.CountryPartType", "CountryPartType")
                        .WithMany("CountryParts")
                        .HasForeignKey("CountryPartTypeId");

                    b.Navigation("CountryPartType");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCompanies.MovieCompany", b =>
                {
                    b.HasOne("CinemaBox.Domain.Entertainment.Coropration.Company", "Company")
                        .WithMany("MovieCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieCompanies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCountries.MovieCountry", b =>
                {
                    b.HasOne("CinemaBox.Domain.Division.CountryParts.CountryPart", "CountryPart")
                        .WithMany("MovieCountries")
                        .HasForeignKey("CountryPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieCountries")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryPart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.HasOne("CinemaBox.Domain.Shared.Currencies.Currency", "Currency")
                        .WithMany("Movies")
                        .HasForeignKey("BudgetCurrencyId");

                    b.HasOne("CinemaBox.Domain.Entertainment.Certificates.Certificate", "Certificate")
                        .WithMany("Movies")
                        .HasForeignKey("CertificateId");

                    b.HasOne("CinemaBox.Domain.Entertainment.Collections.Collection", "Collection")
                        .WithMany("Movies")
                        .HasForeignKey("CollectionId");

                    b.Navigation("Certificate");

                    b.Navigation("Collection");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryPartTypes.CountryPartType", b =>
                {
                    b.Navigation("CountryParts");
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryParts.CountryPart", b =>
                {
                    b.Navigation("MovieCountries");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Certificates.Certificate", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Collections.Collection", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Coropration.Company", b =>
                {
                    b.Navigation("MovieCompanies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.Navigation("MovieCompanies");

                    b.Navigation("MovieCountries");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Currencies.Currency", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
