// <auto-generated />
using System;
using CinemaBox.Context.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaBox.Context.Migrations
{
    [DbContext(typeof(CinemaBoxDbContext))]
    [Migration("20250615184233_InitialDb_V27")]
    partial class InitialDb_V27
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryPartTypes.CountryPartType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CountryPartTypeId")
                        .HasComment("شناسه نوع تقسیم بندی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("CountryPartTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان نوع تقسیم بندی");

                    b.HasKey("Id");

                    b.ToTable("CountryPartTypes", "Division");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CountryPartTypeName = "کشور"
                        },
                        new
                        {
                            Id = (byte)2,
                            CountryPartTypeName = "استان"
                        },
                        new
                        {
                            Id = (byte)3,
                            CountryPartTypeName = "شهرستان"
                        });
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryParts.CountryPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CountryPartId")
                        .HasComment("شناسه کشور");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte?>("CountryPartTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه نوع کشور");

                    b.Property<string>("EnCountryPartName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان انگلیسی");

                    b.Property<string>("FaCountryPartName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان فارسی");

                    b.Property<string>("IsoCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("عنوان نوع تقسیم بندی");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasComment("شناسه پدر");

                    b.HasKey("Id");

                    b.HasIndex("CountryPartTypeId");

                    b.ToTable("CountryParts", "Division");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Certificates.Certificate", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CertificateId")
                        .HasComment("شناسه زده بندی سنی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("نام درجه بندی");

                    b.HasKey("Id");

                    b.ToTable("Certificates", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Collections.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CollectionId")
                        .HasComment("شناسه کالکشن");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnCollectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام کالکشن انگلیسی");

                    b.Property<string>("FaCollectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نام کالکشن فارسی");

                    b.HasKey("Id");

                    b.ToTable("Collections", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Coropration.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CompanyId")
                        .HasComment("شناسه شزکت");

                    b.Property<string>("EnCompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان شرکت انگلیسی");

                    b.Property<string>("FaCompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان شرکت فارسی");

                    b.HasKey("Id");

                    b.ToTable("Companies", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.CreditTypes.CreditType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CreditTypeId")
                        .HasComment("شناسه نوع عوامل");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("EnCreditTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نوع عوامل انگلیسی");

                    b.Property<string>("FaCreditTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نوع عوامل فارسی");

                    b.HasKey("Id");

                    b.ToTable("CreditTypes", "Entertainment");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            EnCreditTypeName = "Director",
                            FaCreditTypeName = "کارگردان"
                        },
                        new
                        {
                            Id = (byte)2,
                            EnCreditTypeName = "Writers",
                            FaCreditTypeName = "نویسنده"
                        },
                        new
                        {
                            Id = (byte)3,
                            EnCreditTypeName = "Cast",
                            FaCreditTypeName = "بازیگران"
                        },
                        new
                        {
                            Id = (byte)4,
                            EnCreditTypeName = "Producers",
                            FaCreditTypeName = "تهیه کنندکان"
                        });
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Genres.Genre", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("GenreId")
                        .HasComment("شناسه ژانر");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("EnGenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("ژانر انگلیسی");

                    b.Property<string>("FaGenreName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("نوع ژانر فارسی");

                    b.Property<long?>("FileId")
                        .HasColumnType("bigint")
                        .HasComment("شناسه فایل");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Genres", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCompanies.MovieCompany", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CompanyId")
                        .HasComment("شناسه شرکت");

                    b.HasKey("MovieId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("MovieCompanies", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCountries.MovieCountry", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<long>("CountryPartId")
                        .HasMaxLength(20)
                        .HasColumnType("bigint")
                        .HasColumnName("CountryPartId")
                        .HasComment("شناسه کشور");

                    b.HasKey("MovieId", "CountryPartId");

                    b.HasIndex("CountryPartId");

                    b.ToTable("MovieCountries", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCredits.MovieCredit", b =>
                {
                    b.Property<string>("PeopleId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PeopleId")
                        .HasComment("شناسه بازیگر");

                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<byte>("CreditTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("خلاصه نوع عامل");

                    b.Property<bool?>("IsLead")
                        .HasColumnType("bit")
                        .HasComment("بازیگر اصلی");

                    b.Property<string>("RoleName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("نام نقش");

                    b.HasKey("PeopleId", "MovieId", "CreditTypeId");

                    b.HasIndex("CreditTypeId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieCredits", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieFiles.MovieFile", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("شناسه فیلم");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasComment("شناسه فایل");

                    b.HasKey("MovieId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("MovieFiles", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieGenres.MovieGenre", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<byte>("GenreId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه ژانر");

                    b.HasKey("MovieId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MovieGenres", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieKeywords.MovieKeyword", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("شناسه فیلم");

                    b.Property<string>("KeywordId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("شناسه کلمه کلیدی");

                    b.HasKey("MovieId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("MovieKeywords", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieLocations.MovieLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("شناسه محل فیلم برداری");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("محل فیلم برداری");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieLocations", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieSpokenLanguages.MovieSpokenLanguage", b =>
                {
                    b.Property<string>("MovieId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.Property<byte>("LanguageId")
                        .HasColumnType("tinyint")
                        .HasColumnName("LanguageId")
                        .HasComment("شناسه زبان");

                    b.HasKey("MovieId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("MovieSpokenLanguages", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieTaglines.MovieTagline", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("شناسه جمله نهایی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("EnTagline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("محل جمله نهایی انگلیسی");

                    b.Property<string>("FaTagline")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("محل جمله نهایی فارسی");

                    b.Property<string>("MovieId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieTaglines", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم یا سریال");

                    b.Property<decimal?>("AggregateRating")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("رتبه بندی کل");

                    b.Property<double?>("Budget")
                        .HasColumnType("float")
                        .HasComment("بودجه");

                    b.Property<byte?>("BudgetCurrencyId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه واحد پول بودجه");

                    b.Property<byte?>("CertificateId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه درجه بندی سنی");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int")
                        .HasComment("شناسه کالکشن");

                    b.Property<string>("EnPlot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("خلاصه داستان انگلیسی");

                    b.Property<string>("EnStoryline")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("داستان انگلیسی");

                    b.Property<string>("EnTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان انگلیسی");

                    b.Property<long?>("EndYear")
                        .HasColumnType("bigint")
                        .HasComment("تاریخ پایان سریال");

                    b.Property<string>("FaStoryline")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("داستان فارسی");

                    b.Property<string>("FaTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان فارسی");

                    b.Property<bool?>("IsTvShow")
                        .HasColumnType("bit")
                        .HasComment("سریال");

                    b.Property<long?>("Nomination")
                        .HasColumnType("bigint")
                        .HasComment("نامزد شدن");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان اصلی");

                    b.Property<byte?>("OscarNominations")
                        .HasColumnType("tinyint")
                        .HasComment("تعداد نامزد اسکار");

                    b.Property<byte?>("OscarWins")
                        .HasColumnType("tinyint")
                        .HasComment("تعداد برنده اسکار");

                    b.Property<long?>("ReleaseDay")
                        .HasColumnType("bigint")
                        .HasComment("روز انتشار");

                    b.Property<long?>("ReleaseMonth")
                        .HasColumnType("bigint")
                        .HasComment("ماه انتشار");

                    b.Property<long?>("ReleaseYear")
                        .HasColumnType("bigint")
                        .HasComment("سال انتشار");

                    b.Property<long?>("RunTimeMinutes")
                        .HasColumnType("bigint")
                        .HasComment("مدت زمان فیلم یا سریال");

                    b.Property<long?>("StartYear")
                        .HasColumnType("bigint")
                        .HasComment("سال فیلم یا سال شروع سریال");

                    b.Property<byte?>("TopRank")
                        .HasColumnType("tinyint")
                        .HasComment("برترین فیلم");

                    b.Property<long?>("VoteCount")
                        .HasColumnType("bigint")
                        .HasComment("تعداد رای دهندگان");

                    b.Property<long?>("Winner")
                        .HasColumnType("bigint")
                        .HasComment("تعداد جوایز");

                    b.HasKey("Id");

                    b.HasIndex("BudgetCurrencyId");

                    b.HasIndex("CertificateId");

                    b.HasIndex("CollectionId");

                    b.ToTable("Movies", "Entertainment");
                });

            modelBuilder.Entity("CinemaBox.Domain.Files.Files.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("FileId")
                        .HasComment("شناسه فایل");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان فایل");

                    b.Property<byte>("ServerId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه  سرور");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Files", "Files");
                });

            modelBuilder.Entity("CinemaBox.Domain.Person.PeopleFiles.PeopleFile", b =>
                {
                    b.Property<string>("PeopleId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("شناسه بازیگر");

                    b.Property<long>("FileId")
                        .HasColumnType("bigint")
                        .HasComment("شناسه فایل");

                    b.HasKey("PeopleId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("PeopleFiles", "Person");
                });

            modelBuilder.Entity("CinemaBox.Domain.Person.Peoples.People", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PeopleId")
                        .HasComment("شناسه زده بندی سنی");

                    b.Property<DateOnly>("AddedDate")
                        .HasColumnType("date")
                        .HasComment("تاریخ اضافه شدن");

                    b.Property<string>("BirthName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("نام تولد");

                    b.Property<DateOnly?>("BornDate")
                        .HasColumnType("date")
                        .HasComment("تاریخ تولد");

                    b.Property<string>("BornPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("محل تولد");

                    b.Property<int?>("DeathCauseId")
                        .HasColumnType("int")
                        .HasComment("شناسه دلیل فوت");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date")
                        .HasComment("تاریخ فوت");

                    b.Property<string>("DeathPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("محل فوت");

                    b.Property<string>("EnFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("نام انگلیسی");

                    b.Property<string>("EnMiniBiography")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("خلاصه زندگینامه انگلیسی");

                    b.Property<string>("FaFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("نام فارسی");

                    b.Property<string>("FaMiniBiography")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("خلاصه زندگینامه فارسی");

                    b.Property<string>("Height")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("قد");

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("معروف");

                    b.Property<DateOnly>("UpdatedDate")
                        .HasColumnType("date")
                        .HasComment("تاریخ بروز شدن");

                    b.HasKey("Id");

                    b.HasIndex("DeathCauseId");

                    b.ToTable("Peoples", "Person");
                });

            modelBuilder.Entity("CinemaBox.Domain.Servers.ServerTypes.ServerType", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("ServerTypeId")
                        .HasComment("شناسه نوع سرور");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("ServerTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان سرور");

                    b.HasKey("Id");

                    b.ToTable("ServerTypes", "Server");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            ServerTypeName = "People"
                        },
                        new
                        {
                            Id = (byte)2,
                            ServerTypeName = "Movie"
                        });
                });

            modelBuilder.Entity("CinemaBox.Domain.Servers.Servers.Server", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("ServerId")
                        .HasComment("شناسه سرور");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Path")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("مسیر");

                    b.Property<string>("ServerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان سرور");

                    b.Property<byte?>("ServerTypeId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه نوع سرور");

                    b.HasKey("Id");

                    b.HasIndex("ServerTypeId");

                    b.ToTable("Servers", "Server");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Path = "Images/People",
                            ServerName = "PeoplePrimaryImage",
                            ServerTypeId = (byte)1
                        },
                        new
                        {
                            Id = (byte)2,
                            Path = "Images/Movie",
                            ServerName = "MoviePrimaryImage",
                            ServerTypeId = (byte)2
                        });
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Currencies.Currency", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("CurrencyId")
                        .HasComment("شناسه واحد پولی");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان واحد پولی");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "Shared");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.DeathCauses.DeathCause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DeathCauseId")
                        .HasComment("شناسه نوع فوت");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnDeathCauseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("عنوان فوت انگلیسی");

                    b.Property<string>("FaDeathCauseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("عنوان فوت فارسی");

                    b.HasKey("Id");

                    b.ToTable("DeathCauses", "Shared");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Keywords.Keyword", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("KeywordId")
                        .HasComment("شناسه کلمه کلیدی");

                    b.Property<string>("EnKeyowrdName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("کلمه کلیدی انگلیسی");

                    b.Property<string>("FaKeyowrdName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("کلمه کلیدی فارسی");

                    b.HasKey("Id");

                    b.ToTable("Keywords", "Shared");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Languages.Language", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("LanguageId")
                        .HasComment("شناسه زبان");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("EnLanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان زبان انگلیسی");

                    b.Property<string>("FaLanguageName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("عنوان زبان فارسی");

                    b.Property<string>("IsoCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("کد زبان");

                    b.HasKey("Id");

                    b.ToTable("Languages", "Shared");
                });

            modelBuilder.Entity("CinemaBox.Domain.Users.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UserId")
                        .HasComment("شناسه کاربر");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasComment("رمز عبور");

                    b.HasKey("Id");

                    b.ToTable("Users", "Usr");
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryParts.CountryPart", b =>
                {
                    b.HasOne("CinemaBox.Domain.Division.CountryPartTypes.CountryPartType", "CountryPartType")
                        .WithMany("CountryParts")
                        .HasForeignKey("CountryPartTypeId");

                    b.Navigation("CountryPartType");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Genres.Genre", b =>
                {
                    b.HasOne("CinemaBox.Domain.Files.Files.File", "File")
                        .WithMany("Genres")
                        .HasForeignKey("FileId");

                    b.Navigation("File");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCompanies.MovieCompany", b =>
                {
                    b.HasOne("CinemaBox.Domain.Entertainment.Coropration.Company", "Company")
                        .WithMany("MovieCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieCompanies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCountries.MovieCountry", b =>
                {
                    b.HasOne("CinemaBox.Domain.Division.CountryParts.CountryPart", "CountryPart")
                        .WithMany("MovieCountries")
                        .HasForeignKey("CountryPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieCountries")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryPart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieCredits.MovieCredit", b =>
                {
                    b.HasOne("CinemaBox.Domain.Entertainment.CreditTypes.CreditType", "CreditType")
                        .WithMany("MovieCredits")
                        .HasForeignKey("CreditTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieCredits")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Person.Peoples.People", "People")
                        .WithMany("MovieCredits")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditType");

                    b.Navigation("Movie");

                    b.Navigation("People");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieFiles.MovieFile", b =>
                {
                    b.HasOne("CinemaBox.Domain.Files.Files.File", "File")
                        .WithMany("MovieFiles")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieFiles")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieGenres.MovieGenre", b =>
                {
                    b.HasOne("CinemaBox.Domain.Entertainment.Genres.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieKeywords.MovieKeyword", b =>
                {
                    b.HasOne("CinemaBox.Domain.Shared.Keywords.Keyword", "Keyword")
                        .WithMany("MovieKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieKeywords")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieLocations.MovieLocation", b =>
                {
                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieLocations")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieSpokenLanguages.MovieSpokenLanguage", b =>
                {
                    b.HasOne("CinemaBox.Domain.Shared.Languages.Language", "Language")
                        .WithMany("MovieSpokenLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieSpokenLanguages")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Link.MovieTaglines.MovieTagline", b =>
                {
                    b.HasOne("CinemaBox.Domain.Entertainment.Movies.Movie", "Movie")
                        .WithMany("MovieTaglines")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.HasOne("CinemaBox.Domain.Shared.Currencies.Currency", "Currency")
                        .WithMany("Movies")
                        .HasForeignKey("BudgetCurrencyId");

                    b.HasOne("CinemaBox.Domain.Entertainment.Certificates.Certificate", "Certificate")
                        .WithMany("Movies")
                        .HasForeignKey("CertificateId");

                    b.HasOne("CinemaBox.Domain.Entertainment.Collections.Collection", "Collection")
                        .WithMany("Movies")
                        .HasForeignKey("CollectionId");

                    b.Navigation("Certificate");

                    b.Navigation("Collection");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("CinemaBox.Domain.Files.Files.File", b =>
                {
                    b.HasOne("CinemaBox.Domain.Servers.Servers.Server", "Server")
                        .WithMany("Files")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("CinemaBox.Domain.Person.PeopleFiles.PeopleFile", b =>
                {
                    b.HasOne("CinemaBox.Domain.Files.Files.File", "File")
                        .WithMany("PeopleFiles")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaBox.Domain.Person.Peoples.People", "People")
                        .WithMany("PeopleFiles")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("People");
                });

            modelBuilder.Entity("CinemaBox.Domain.Person.Peoples.People", b =>
                {
                    b.HasOne("CinemaBox.Domain.Shared.DeathCauses.DeathCause", "DeathCause")
                        .WithMany("People")
                        .HasForeignKey("DeathCauseId");

                    b.Navigation("DeathCause");
                });

            modelBuilder.Entity("CinemaBox.Domain.Servers.Servers.Server", b =>
                {
                    b.HasOne("CinemaBox.Domain.Servers.ServerTypes.ServerType", "ServerType")
                        .WithMany("Servers")
                        .HasForeignKey("ServerTypeId");

                    b.Navigation("ServerType");
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryPartTypes.CountryPartType", b =>
                {
                    b.Navigation("CountryParts");
                });

            modelBuilder.Entity("CinemaBox.Domain.Division.CountryParts.CountryPart", b =>
                {
                    b.Navigation("MovieCountries");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Certificates.Certificate", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Collections.Collection", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Coropration.Company", b =>
                {
                    b.Navigation("MovieCompanies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.CreditTypes.CreditType", b =>
                {
                    b.Navigation("MovieCredits");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Genres.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.Navigation("MovieCompanies");

                    b.Navigation("MovieCountries");

                    b.Navigation("MovieCredits");

                    b.Navigation("MovieFiles");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieKeywords");

                    b.Navigation("MovieLocations");

                    b.Navigation("MovieSpokenLanguages");

                    b.Navigation("MovieTaglines");
                });

            modelBuilder.Entity("CinemaBox.Domain.Files.Files.File", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("MovieFiles");

                    b.Navigation("PeopleFiles");
                });

            modelBuilder.Entity("CinemaBox.Domain.Person.Peoples.People", b =>
                {
                    b.Navigation("MovieCredits");

                    b.Navigation("PeopleFiles");
                });

            modelBuilder.Entity("CinemaBox.Domain.Servers.ServerTypes.ServerType", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("CinemaBox.Domain.Servers.Servers.Server", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Currencies.Currency", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.DeathCauses.DeathCause", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Keywords.Keyword", b =>
                {
                    b.Navigation("MovieKeywords");
                });

            modelBuilder.Entity("CinemaBox.Domain.Shared.Languages.Language", b =>
                {
                    b.Navigation("MovieSpokenLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
