// <auto-generated />
using CinemaBox.Context.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaBox.Context.Migrations
{
    [DbContext(typeof(CinemaBoxDbContext))]
    [Migration("20250614132939_InitialDb_V0")]
    partial class InitialDb_V0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaBox.Domain.Entertainment.Movies.Movie", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MovieId")
                        .HasComment("شناسه فیلم یا سریال");

                    b.Property<decimal?>("AggregateRating")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("رتبه بندی کل");

                    b.Property<double?>("Budget")
                        .HasColumnType("float")
                        .HasComment("بودجه");

                    b.Property<byte?>("BudgetCurrencyId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه واحد پول بودجه");

                    b.Property<byte?>("CertificateId")
                        .HasColumnType("tinyint")
                        .HasComment("شناسه درجه بندی سنی");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int")
                        .HasComment("شناسه کالکشن");

                    b.Property<string>("EnPlot")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("خلاصه داستان انگلیسی");

                    b.Property<string>("EnStoryline")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("داستان انگلیسی");

                    b.Property<string>("EnTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان انگلیسی");

                    b.Property<long?>("EndYear")
                        .HasColumnType("bigint")
                        .HasComment("تاریخ پایان سریال");

                    b.Property<string>("FaStoryline")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasComment("داستان فارسی");

                    b.Property<string>("FaTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان فارسی");

                    b.Property<bool?>("IsTvShow")
                        .HasColumnType("bit")
                        .HasComment("سریال");

                    b.Property<long?>("Nomination")
                        .HasColumnType("bigint")
                        .HasComment("نامزد شدن");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("عنوان اصلی");

                    b.Property<byte?>("OscarNominations")
                        .HasColumnType("tinyint")
                        .HasComment("تعداد نامزد اسکار");

                    b.Property<byte?>("OscarWins")
                        .HasColumnType("tinyint")
                        .HasComment("تعداد برنده اسکار");

                    b.Property<long?>("ReleaseDay")
                        .HasColumnType("bigint")
                        .HasComment("روز انتشار");

                    b.Property<long?>("ReleaseMonth")
                        .HasColumnType("bigint")
                        .HasComment("ماه انتشار");

                    b.Property<long?>("ReleaseYear")
                        .HasColumnType("bigint")
                        .HasComment("سال انتشار");

                    b.Property<long?>("RunTimeMinutes")
                        .HasColumnType("bigint")
                        .HasComment("مدت زمان فیلم یا سریال");

                    b.Property<long?>("StartYear")
                        .HasColumnType("bigint")
                        .HasComment("سال فیلم یا سال شروع سریال");

                    b.Property<byte?>("TopRank")
                        .HasColumnType("tinyint")
                        .HasComment("برترین فیلم");

                    b.Property<long?>("VoteCount")
                        .HasColumnType("bigint")
                        .HasComment("تعداد رای دهندگان");

                    b.Property<long?>("Winner")
                        .HasColumnType("bigint")
                        .HasComment("تعداد جوایز");

                    b.HasKey("Id");

                    b.ToTable("Movies", "Entertainment");
                });
#pragma warning restore 612, 618
        }
    }
}
